### ISSUE TITLE
Error during redisplay: (eval (lsp-mode-line)) signaled (wrong-type-argument lsp--workspace nil) [6 times]

### ISSUE THREAD

**Issue by dabrahams** [emacs-lsp/lsp-sourcekit#4]
Pursuant to #3, I tried using this on sourcekit-lsp itself, which is a SwiftPM project, but I just keep getting 

```
Error during redisplay: (eval (lsp-mode-line)) signaled (wrong-type-argument lsp--workspace nil) [6 times]
```

Ideas?

**Comment by yyoncho** [comment]
@danielmartin - lsp-sourcekit should me migrated to latest lsp.el since there was a breaking change- https://github.com/emacs-lsp/lsp-mode#whats-new-in-lspel

**Comment by danielmartin** [comment]
OK, the extension has been updated to the new `lsp-mode` API. It requires a current `lsp-mode` that contains the Swift language identifier (https://github.com/emacs-lsp/lsp-mode/commit/6733e449b6f7a8dea8083df81bda44a0bf929795). I've tested it locally and works well. @dabrahams, can you check if updating to the latest version solves your issue?

**Comment by yyoncho** [comment]
Should have been fixed in the past. Please reopen if it happens again.
